development:
  adapter:  postgresql
  host:     ""
  encoding: unicode
  database: active_segments_acceptance
  username: postgres
  password: password
  pool:     18
  template: template0

test:
  adapter:  postgresql
  host:     ""
  encoding: unicode
  database: active_segments_test
  username: postgres
  password: password
  pool:     18
  template: template0

production:
  adapter:  postgresql
  host:     ""
  encoding: unicode
  database: active_segments_production
  username: postgress
  password: password
  template: template0
  url:      <%= ENV["DATABASE_URL"] %>
  pool:     18
